CREATE SEQUENCE S_ACCOUNT_ID;

CREATE TABLE ACCOUNT (
  ID NUMBER DEFAULT S_ACCOUNT_ID.NEXTVAL NOT NULL,
  AMOUNT NUMBER NOT NULL
);

ALTER TABLE ACCOUNT ADD CONSTRAINT PK_ACCOUNT_ID PRIMARY KEY (ID);